version: "3.2"

volumes:
  tereus_db:
  tereus_minio:

networks:
  tereus_api:
    name: tereus_api
  tereus_workers:
    name: tereus_workers

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - tereus_api
      - tereus_workers
    ports:
      - 5672:5672
      - 15672:15672
    restart: always

  postgres:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
      POSTGRES_DB: tereus
    volumes:
      - tereus_db:/data
    networks:
      - tereus_api
    ports:
      - 5432:5432
    restart: always

  minio:
    image: minio/minio
    volumes:
      - tereus_minio:/data
    environment:
      # MINIO_ROOT_USER: miniokey
      # MINIO_ROOT_PASSWORD: miniosecret
      MINIO_ACCESS_KEY: miniokey
      MINIO_SECRET_KEY: miniosecret
    command: server --console-address ":9001" /data
    networks:
      - tereus_api
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    restart: always

  api:
    image: cosmtrek/air
    networks:
      - tereus_api
    ports:
      - 1323:1323
    volumes:
      - ./:/app
    env_file: .env
    environment:
      air_wd: /app
    tty: true
