app = "tereus-api"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  DATABASE_DRIVER = "postgres"
  ENV = "prod"
  LOG_LEVEL = "debug"
  S3_BUCKET = "tereus"
  S3_ENDPOINT = "ams3.digitaloceanspaces.com"
  S3_HTTPS_ENABLED = "true"
  SUBMISSIONS_FOLDER = "transpilations-results"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 1323
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
