name: Push workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - linux
          - darwin
          - freebsd
          - windows
        arch:
          - amd64
          - arm64
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Run build
        run: go build -o tereus-api-$GOOS-$GOARCH
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
